language: ruby
rvm:
 - 2.4.1

cache: bundler

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  # - ruby ~/turing/3module/projects/pink_flamingo_microservice/app/controllers/twilio_service.rb
  - /turing/3module/projects/pink_flamingo_microservice/app/controllers
  - "bundle exec rails server -p 3000 -d"

script: bundle exec rspec

before_script:
  - psql -c 'create database twilio_test;' -U postgres
