language: ruby
rvm:
 - 2.4.1

cache: bundler

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - ~/turing/3module/projects/pink_flamingo_microservice/app/controllers ruby twilio_service.rb

script: bundle exec rspec
