development:
 facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
 facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
test:
 facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
 facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
production:
 facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
 facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
